### ISSUE TITLE
测试结果和官方的有点差别，官方的更接近

### ISSUE THREAD

**Issue by yuexiajiayan** [DakeQQ/Audio-Denoiser-ONNX#1]
![1](https://github.com/user-attachments/assets/181b9f50-a06f-438f-88c3-1952e0414b0b)
测试音频修改下后缀wav

https://github.com/user-attachments/assets/d3bc98e7-2d70-46c5-96a4-14b66d13daf2

@DakeQQ

**Comment by DakeQQ** [comment]
您可以通过调整 `INPUT_AUDIO_LENGTH = 24000` 或设置 `DYNAMIC_AXES = True` 来导出自定义的 ZipEnhancer 模型。默认情况下，该模型将音频切分为 250ms 的片段，以实现实时推理速度。（我们在 ASR 模型之前使用此降噪模型，因此将其配置为接受 250ms 的输入。）增加 ZipEnhancer 模型的输入片段大小可以提升输出的清晰度，使其更接近官方版本。

**Comment by yuexiajiayan** [comment]
> 您可以通过调整`MAX_SIGNAL_LENGTH=1024` , `INPUT_AUDIO_LENGTH = 32000或更大` ,或设置 `DYNAMIC_AXES = True` 来导出自定义的 ZipEnhancer 模型。默认情况下，该模型将音频切分为 250ms 的片段，以实现实时推理速度。（我们在 ASR 模型之前使用此降噪模型，因此将其配置为接受 250ms 的输入。然而，250ms 版本中残留的噪声或过度降噪对 ASR 模型来说仍然可以接受。）增加 ZipEnhancer 模型的输入片段大小可以提升输出的清晰度，使其更接近官方版本。

ok谢谢
